// Generated by LiveScript 1.2.0
(function(){
  $(document).ready(function(){
    var fs, path, irc, net, users, stream, client, mynick, mychannel, content, chat, input;
    fs = require('fs');
    path = require('path');
    irc = require('slate-irc');
    net = require('net');
    users = {};
    function addUser(name){
      var hue, color;
      hue = Math.floor(Math.random() * 360 + 1);
      color = pusher.color("#2e95c1").hue(hue).hex6();
      return users[name] = color;
    }
    function youtube_parser(url){
      var regExp, m;
      regExp = /.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#\&\?^\s]*).*/;
      m = url.match(regExp);
      console.log(m);
      if (m && m[1].length === 11) {
        return m[1];
      } else {
        console.log('nope');
        return null;
      }
    }
    stream = net.connect({
      port: 6667,
      host: 'irc.freenode.org'
    });
    client = irc(stream);
    mynick = 'moopmoop';
    mychannel = '#reddit-gamedev';
    client.pass('pass');
    client.nick(mynick);
    client.user('tobi', 'Tobi Ferret');
    client.join(mychannel);
    client.names(mychannel, function(err, names){
      var i$, len$, user, results$ = [];
      console.log(names);
      for (i$ = 0, len$ = names.length; i$ < len$; ++i$) {
        user = names[i$];
        results$.push(addUser(user.name));
      }
      return results$;
    });
    content = $('#content');
    chat = $('#content table');
    input = $('#input');
    function scrollDown(){
      $(content).animate({
        scrollTop: $(content)[0].scrollHeight
      }, "slow");
      return console.log('content_height_' + $(content)[0].scrollHeight);
    }
    function displayMsg(msg, author){
      var youtubeid, tr;
      youtubeid = youtube_parser(msg);
      console.log('youtubeid_' + youtubeid);
      if (youtubeid !== null) {
        msg += "<iframe type='text/html' width='340' height='240' src='http://www.youtube.com/embed/" + youtubeid + "' frameborder='0'/>";
      }
      tr = $('<tr><td class="author">' + author + '<div class="square"></div></td><td class="square"><div></div></td><td class="message">' + msg + '</td></tr>');
      chat.append(tr);
      tr.find('.square div').css('background-color', users[author]);
      return scrollDown();
    }
    client.on('message', function(msg){
      console.log(msg);
      return displayMsg(msg.message, msg.from);
    });
    client.on('join', function(event){
      console.log(event);
      return addUser(event.nick);
    });
    input.keypress(function(){
      if (event.which === 13) {
        client.send(mychannel, input.val());
        displayMsg(input.val(), mynick);
        return input.val("");
      }
    });
    scrollDown();
  });
}).call(this);
